/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package avaiserexcluido;

import javax.swing.JOptionPane;

/**
 *
 * @author EDYA
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuCidades = new javax.swing.JMenuItem();
        menuPessoas = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        menuAjudaDescricao = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro de Pessoas");
        setBackground(new java.awt.Color(255, 102, 0));

        jMenu1.setText("Cadastros");

        menuCidades.setText("CRUD de Cidades");
        menuCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCidadesActionPerformed(evt);
            }
        });
        jMenu1.add(menuCidades);

        menuPessoas.setText("CRUD de Pessoas");
        menuPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPessoasActionPerformed(evt);
            }
        });
        jMenu1.add(menuPessoas);

        jMenuBar1.add(jMenu1);

        menuAjuda.setText("Ajuda");

        menuAjudaDescricao.setText("Descrição");
        menuAjudaDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAjudaDescricaoActionPerformed(evt);
            }
        });
        menuAjuda.add(menuAjudaDescricao);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCidadesActionPerformed
        FormCidade formCidade = new FormCidade(this, true);
        formCidade.setLocationRelativeTo(null);
        formCidade.setResizable(false);
        formCidade.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        formCidade.setVisible(true);
        
        
    }//GEN-LAST:event_menuCidadesActionPerformed

    private void menuPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoasActionPerformed
        FormPessoa10 formPessoa = new FormPessoa10(this, true);
        formPessoa.setLocationRelativeTo(null);
        formPessoa.setResizable(false);
        formPessoa.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        formPessoa.setVisible(true);
        
        
    }//GEN-LAST:event_menuPessoasActionPerformed

    private void menuAjudaDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAjudaDescricaoActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Descrição da ajuda forneceida aqui");
    }//GEN-LAST:event_menuAjudaDescricaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormPrincipal formPrincipal = new FormPrincipal();
                formPrincipal.setVisible(true);
                formPrincipal.setDefaultCloseOperation(EXIT_ON_CLOSE);
                formPrincipal.setLocationRelativeTo(null);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenuItem menuAjudaDescricao;
    private javax.swing.JMenuItem menuCidades;
    private javax.swing.JMenuItem menuPessoas;
    // End of variables declaration//GEN-END:variables
}
