/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cabstracttablemodelcidadepessoa;

/**
 *
 * @author EDYA
 */
public class CRUDPrincipal extends javax.swing.JFrame {
    /**
     * NÃO PRECISAVA PASSAR ESSAS VARIÁVEIS PARA A OUTRA CLASSE SE FOSSE BANCO
    */
    private CidadeDAORAM cidadeDAORAM = null;
    private PessoaDAORAM pessoaDAORAM = null;

    public CidadeDAORAM getCidadeDAORAM() {
        return cidadeDAORAM;
    }

    public void setCidadeDAORAM(CidadeDAORAM cidadeDAORAM) {
        this.cidadeDAORAM = cidadeDAORAM;
    }

    public PessoaDAORAM getPessoaDAORAM() {
        return pessoaDAORAM;
    }

    public void setPessoaDAORAM(PessoaDAORAM pessoaDAORAM) {
        this.pessoaDAORAM = pessoaDAORAM;
    }

    /**
     * Creates new form FormPrincipal
     */
    public CRUDPrincipal() {
        initComponents();
        this.cidadeDAORAM = new CidadeDAORAM();
        this.pessoaDAORAM = new PessoaDAORAM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();
        menuCadastros = new javax.swing.JMenu();
        menuPessoas = new javax.swing.JMenuItem();
        menuCidades = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Cadastro de Pessoas e Cidades");

        menuCadastros.setText("Cadastros");
        menuCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrosActionPerformed(evt);
            }
        });

        menuPessoas.setText("CRUD Pessoas");
        menuPessoas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPessoasActionPerformed(evt);
            }
        });
        menuCadastros.add(menuPessoas);

        menuCidades.setText("CRUD Cidades");
        menuCidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCidadesActionPerformed(evt);
            }
        });
        menuCadastros.add(menuCidades);

        barraMenu.add(menuCadastros);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 357, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuPessoasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPessoasActionPerformed
        CRUDPessoa formPessoa = new CRUDPessoa(); //
        
        formPessoa.setLocationRelativeTo(null);
        formPessoa.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        formPessoa.setResizable(false);
        formPessoa.setVisible(true);    
        formPessoa.setCidadeDAORAM(cidadeDAORAM);
        formPessoa.setPessoaDAORAM(pessoaDAORAM);
        formPessoa.initializePersonalComponents();
    }//GEN-LAST:event_menuPessoasActionPerformed

    private void menuCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuCadastrosActionPerformed

    private void menuCidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCidadesActionPerformed
    
        CRUDCidade formCidade = new CRUDCidade();
        
        formCidade.setLocationRelativeTo(null);
        formCidade.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        formCidade.setResizable(false);
        formCidade.setVisible(true);   
        formCidade.setCidadeDAORAM(cidadeDAORAM);
        formCidade.initializePersonalComponents();
    }//GEN-LAST:event_menuCidadesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUDPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUDPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUDPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUDPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CRUDPrincipal formPrincipal = new CRUDPrincipal();
                formPrincipal.setVisible(true);
                formPrincipal.setLocationRelativeTo(null);

                //change background color
                //formPrincipal.getContentPane().setBackground(Color.red);


                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JMenu menuCadastros;
    private javax.swing.JMenuItem menuCidades;
    private javax.swing.JMenuItem menuPessoas;
    // End of variables declaration//GEN-END:variables
}
